.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nilabit_qt test_nilabit_qt
clean: FORCE
	$(MAKE) -C .. nilabit_qt_clean test_nilabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_nilabit_qt_check
nilabit-qt nilabit-qt.exe: FORCE
	 $(MAKE) -C .. nilabit_qt
