.TH nilabit-CLI "1" "February 2016" "nilabit-cli 0.12"
.SH NAME
nilabit-cli \- a remote procedure call client for Nilabit Core. 
.SH SYNOPSIS
nilabit-cli [options] <command> [params] \- Send command to Nilabit Core. 
.TP
nilabit-cli [options] help \- Asks Nilabit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the nilabit-cli program. nilabit-cli is an RPC client used to send commands to Nilabit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbitcoind\fP, \fBnilabit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
